#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 10 05:11:31 UTC 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
